// Client-side key -> component map for the product-icons catalogue
// (@pos/shared/product-icons). Named imports only (never dynamicIconImports):
// next.config.ts's optimizePackageImports for lucide-react tree-shakes a
// hand-picked list like this one at build time, and the whole catalogue is a
// small, fixed 67-icon set — nowhere near worth lazy-loading per icon.
//
// Every kebab-case key below is the PascalCase lucide-react export for it
// (lucide's own kebab -> PascalCase convention), verified against the
// installed lucide-react version's named exports.
import type { LucideIcon } from "lucide-react";
import {
  Coffee,
  CupSoda,
  Milk,
  GlassWater,
  Citrus,
  Beer,
  Wine,
  BottleWine,
  Martini,
  Hop,
  Pizza,
  Hamburger,
  Sandwich,
  Salad,
  Soup,
  CookingPot,
  Drumstick,
  Ham,
  Beef,
  Fish,
  Shrimp,
  Egg,
  EggFried,
  Croissant,
  Cookie,
  Donut,
  Cake,
  CakeSlice,
  Dessert,
  IceCreamCone,
  IceCreamBowl,
  Popsicle,
  Lollipop,
  Candy,
  CandyCane,
  Popcorn,
  Apple,
  Banana,
  Cherry,
  Grape,
  Carrot,
  Bean,
  Nut,
  Wheat,
  Leaf,
  LeafyGreen,
  Sprout,
  Vegan,
  ChefHat,
  Utensils,
  UtensilsCrossed,
  Flame,
  FlameKindling,
  Microwave,
  Refrigerator,
  Snowflake,
  ThermometerSun,
  Sparkles,
  Star,
  Heart,
  Crown,
  Award,
  Gift,
  Percent,
  Package,
  ShoppingBag,
  Store,
} from "lucide-react";

import { isProductIconKey, type ProductIconKey } from "@pos/shared/product-icons";

const PRODUCT_ICON_COMPONENTS: Record<ProductIconKey, LucideIcon> = {
  coffee: Coffee,
  "cup-soda": CupSoda,
  milk: Milk,
  "glass-water": GlassWater,
  citrus: Citrus,
  beer: Beer,
  wine: Wine,
  "bottle-wine": BottleWine,
  martini: Martini,
  hop: Hop,
  pizza: Pizza,
  hamburger: Hamburger,
  sandwich: Sandwich,
  salad: Salad,
  soup: Soup,
  "cooking-pot": CookingPot,
  drumstick: Drumstick,
  ham: Ham,
  beef: Beef,
  fish: Fish,
  shrimp: Shrimp,
  egg: Egg,
  "egg-fried": EggFried,
  croissant: Croissant,
  cookie: Cookie,
  donut: Donut,
  cake: Cake,
  "cake-slice": CakeSlice,
  dessert: Dessert,
  "ice-cream-cone": IceCreamCone,
  "ice-cream-bowl": IceCreamBowl,
  popsicle: Popsicle,
  lollipop: Lollipop,
  candy: Candy,
  "candy-cane": CandyCane,
  popcorn: Popcorn,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  grape: Grape,
  carrot: Carrot,
  bean: Bean,
  nut: Nut,
  wheat: Wheat,
  leaf: Leaf,
  "leafy-green": LeafyGreen,
  sprout: Sprout,
  vegan: Vegan,
  "chef-hat": ChefHat,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  flame: Flame,
  "flame-kindling": FlameKindling,
  microwave: Microwave,
  refrigerator: Refrigerator,
  snowflake: Snowflake,
  "thermometer-sun": ThermometerSun,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  crown: Crown,
  award: Award,
  gift: Gift,
  percent: Percent,
  package: Package,
  "shopping-bag": ShoppingBag,
  store: Store,
};

// Renders no icon for an unknown or prototype-polluting key ("constructor",
// "toString", ...) — isProductIconKey does the Object.hasOwn check, so a
// stale/garbage stored value is exactly "no icon", never a thrown lookup.
export function productIconComponent(key: string | undefined): LucideIcon | null {
  if (!isProductIconKey(key)) return null;
  return PRODUCT_ICON_COMPONENTS[key];
}
